# Kaniko でビルド（レイヤーキャッシュ有効）。マルチステージの builder 層もキャッシュされ、コードのみ変更時は 2〜3 分程度で完了する想定。
steps:
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - --destination=asia-northeast1-docker.pkg.dev/$PROJECT_ID/deepfilternet/deep-filter-net:$COMMIT_SHA
      - --destination=asia-northeast1-docker.pkg.dev/$PROJECT_ID/deepfilternet/deep-filter-net:latest
      - --cache=true
      - --cache-repo=asia-northeast1-docker.pkg.dev/$PROJECT_ID/deepfilternet/build-cache
      - --cache-ttl=168h
      - '--verbosity=info'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'deep-filter-net'
      - '--image'
      - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/deepfilternet/deep-filter-net:$COMMIT_SHA'
      - '--region'
      - 'asia-northeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'

# Kaniko が直接プッシュするため images は指定しない（指定すると Cloud Build が検証で失敗する）
timeout: 1800s

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
